POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
# Authorization: Bearer

mutation CreateUser($data:CreateCategoryInput!){
  createCategory(data: $data){
    id
    code
    name
    description
  }
}

{
  "data": {
    "name": "Produtos de limpeza",
    "description": "Produtos de limpeza em geral"
  }
}