POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
# Authorization: Bearer

mutation CreateUser($data:CreateUserInput!){
  createUser(data: $data){
    id
    name
    email
    password
    roles
    department{
      name
      description
    }
  }
}

# {
#   "data": {
#     "email": "email2@mail.com",
#     "password": "123",
#     "roles": "Manager",
#     "name": "Cesar"
#   }
# }

{
  "data": {
    "email": "email@mail.com",
    "password": "123",
    "roles": "Admin",
    "name": "Caio"
  }
}