POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
# Authorization: Bearer

mutation Login ($data: SignInInput!) {
  login(data: $data) {
    user {
      name
      email
      password
      profileImage
      roles
      id
    }
    accessToken {
      token
      expiresIn
    }
    refreshToken {
      token
      expiresIn
    }
  }
}

{
  "data": {
    "email": "email3@mail.com",
    "password": "123"
  }
}