POST http://localhost:4000/graphql
Content-Type: application/json
# Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

mutation CreateAnalysis($data: CreateAnalysisInput!){
  createAnalysis(data: $data){
    id
    createdAt
    isApproved
    analyst{
        id
        name
        email
        roles
        department{
          code
          name
        }
    }
    order{
        code
        requester{
            id
            name
            email
            roles
            department{
              code
              name
            }
        }
        item{
            name
            description
            value
            categories{
              code
              name
            }
        }
    }
  }
}

{
  "data": {
    "isApproved": true,
    "analystId": 1,
    "orderId": 1
  }
}