POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
# Authorization: Bearer

query GetOrder($code:String!){
  getOrderByCode(code:$code){
    id
    code
    createdAt
    updatedAt
    requesterId
    item{
      name
      description
      value
      imagePath
      id
    }
    analysis{
      id
      updatedAt
      isApproved
      analystId
    }
  }
}

{
  "code": "0399e31d-9f44-4f49-97a3-197f47ee196e"
}